# Generated by Django 5.2.15 on 2026-07-01 07:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementOpening',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.CharField(db_index=True, max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('ctc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('eligibility', models.CharField(blank=True, default='', max_length=512)),
                ('last_date', models.DateField()),
                ('logo_color', models.CharField(blank=True, default='#13327F', max_length=16)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Placement opening',
                'verbose_name_plural': 'Placement openings',
                'ordering': ['-last_date', 'company'],
            },
        ),
        migrations.CreateModel(
            name='PlacementApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected'), ('rejected', 'Rejected')], db_index=True, default='applied', max_length=16)),
                ('applied_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_applications', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='placement.placementopening')),
            ],
            options={
                'verbose_name': 'Placement application',
                'verbose_name_plural': 'Placement applications',
                'ordering': ['-applied_on'],
            },
        ),
        migrations.AddIndex(
            model_name='placementopening',
            index=models.Index(fields=['is_active', 'last_date'], name='placement_p_is_acti_9a455d_idx'),
        ),
        migrations.AddIndex(
            model_name='placementapplication',
            index=models.Index(fields=['student', 'status'], name='placement_p_student_9d53a1_idx'),
        ),
        migrations.AddIndex(
            model_name='placementapplication',
            index=models.Index(fields=['opening', 'status'], name='placement_p_opening_9d7025_idx'),
        ),
        migrations.AddConstraint(
            model_name='placementapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('opening', 'student'), name='uniq_active_application_per_student_opening'),
        ),
    ]
