# Generated by Django 5.2.15 on 2026-07-01 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, default='', max_length=128)),
                ('subject_codes', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculty_profiles', to='academics.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Profile',
                'verbose_name_plural': 'Faculty Profiles',
                'ordering': ['user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='FacultyClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, default='', max_length=9)),
                ('slots', models.JSONField(blank=True, default=list)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_classes', to='academics.section')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_classes', to='academics.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_classes', to='academics.subject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='faculty.facultyprofile')),
            ],
            options={
                'verbose_name': 'Faculty Class',
                'verbose_name_plural': 'Faculty Classes',
                'ordering': ['subject__code'],
            },
        ),
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('student_ref', models.UUIDField(blank=True, db_index=True, null=True)),
                ('roll_no', models.CharField(max_length=32)),
                ('student_name', models.CharField(max_length=255)),
                ('avatar_color', models.CharField(blank=True, default='', max_length=9)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('faculty_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='faculty.facultyclass')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roster Entry',
                'verbose_name_plural': 'Roster Entries',
                'ordering': ['roll_no'],
            },
        ),
        migrations.AddIndex(
            model_name='facultyprofile',
            index=models.Index(fields=['department'], name='faculty_fac_departm_0d602b_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyclass',
            index=models.Index(fields=['faculty'], name='faculty_fac_faculty_fcebbc_idx'),
        ),
        migrations.AddIndex(
            model_name='facultyclass',
            index=models.Index(fields=['subject', 'section'], name='faculty_fac_subject_a68a97_idx'),
        ),
        migrations.AddIndex(
            model_name='rosterentry',
            index=models.Index(fields=['faculty_class'], name='faculty_ros_faculty_1596f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='rosterentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('faculty_class', 'roll_no'), name='uniq_roster_class_rollno'),
        ),
    ]
