# Generated by Django 5.2.15 on 2026-07-01 07:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('warden', models.CharField(blank=True, default='', max_length=255)),
                ('warden_phone', models.CharField(blank=True, default='', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hostel block',
                'verbose_name_plural': 'Hostel blocks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('room_no', models.CharField(db_index=True, max_length=32)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hostel.hostelblock')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hostel room',
                'verbose_name_plural': 'Hostel rooms',
                'ordering': ['block', 'room_no'],
            },
        ),
        migrations.CreateModel(
            name='HostelAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bed', models.CharField(blank=True, default='', max_length=32)),
                ('mess_plan', models.CharField(blank=True, default='', max_length=128)),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocation', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='hostel.hostelroom')),
            ],
            options={
                'verbose_name': 'Hostel allocation',
                'verbose_name_plural': 'Hostel allocations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hostelroom',
            index=models.Index(fields=['block', 'room_no'], name='hostel_host_block_i_f2e258_idx'),
        ),
        migrations.AddConstraint(
            model_name='hostelroom',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('block', 'room_no'), name='uniq_room_no_per_block'),
        ),
        migrations.AddIndex(
            model_name='hostelallocation',
            index=models.Index(fields=['room'], name='hostel_host_room_id_88c228_idx'),
        ),
    ]
