# Generated by Django 5.2.15 on 2026-07-01 07:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('issuer', models.CharField(blank=True, default='', max_length=255)),
                ('issued_on', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('kind', models.CharField(choices=[('course', 'Course'), ('event', 'Event'), ('achievement', 'Achievement')], db_index=True, default='course', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('url', models.URLField(blank=True, default='', max_length=1024)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_on', '-created_at'],
                'indexes': [models.Index(fields=['student', 'kind'], name='certificate_student_d0266a_idx'), models.Index(fields=['student', 'issued_on'], name='certificate_student_b3e7c1_idx')],
            },
        ),
    ]
