# Generated by Django 5.2.15 on 2026-07-01 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('time', models.CharField(blank=True, default='', max_length=32)),
                ('room', models.CharField(blank=True, default='', max_length=64)),
                ('duration_mins', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('Internal', 'Internal'), ('Semester', 'Semester'), ('Quiz', 'Quiz')], db_index=True, default='Internal', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.subject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.CharField(blank=True, default='', max_length=128)),
                ('marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('grade', models.CharField(blank=True, default='', max_length=8)),
                ('grade_point', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('credits', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('exam_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='academics.subject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Result',
                'verbose_name_plural': 'Exam Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarksSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.CharField(max_length=128)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('entered_on', models.DateTimeField(db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('faculty_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_sheets', to='faculty.facultyclass')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marks Sheet',
                'verbose_name_plural': 'Marks Sheets',
                'ordering': ['-entered_on'],
            },
        ),
        migrations.CreateModel(
            name='MarkEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('marks', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_entries', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='exams.markssheet')),
            ],
            options={
                'verbose_name': 'Mark Entry',
                'verbose_name_plural': 'Mark Entries',
                'ordering': ['student__roll_no'],
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['subject', 'date'], name='exams_exam_subject_153e59_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['date', 'type'], name='exams_exam_date_81d8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student', 'subject'], name='exams_examr_student_3f8ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student'], name='exams_examr_student_dfce85_idx'),
        ),
        migrations.AddIndex(
            model_name='markssheet',
            index=models.Index(fields=['faculty_class'], name='exams_marks_faculty_d4ce38_idx'),
        ),
        migrations.AddConstraint(
            model_name='markssheet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('faculty_class', 'exam'), name='uniq_markssheet_class_exam'),
        ),
        migrations.AddIndex(
            model_name='markentry',
            index=models.Index(fields=['sheet'], name='exams_marke_sheet_i_787736_idx'),
        ),
        migrations.AddConstraint(
            model_name='markentry',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sheet', 'student'), name='uniq_markentry_sheet_student'),
        ),
    ]
