# Generated by Django 5.2.15 on 2026-07-01 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('feature', models.CharField(choices=[('mentor', 'AI Mentor'), ('doubt', 'AI Doubt Solver'), ('notes', 'AI Lecture Notes'), ('assignment', 'AI Assignment Helper'), ('resume', 'AI Resume Analyzer'), ('career', 'AI Career Guide'), ('chat', 'AI Assistant')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Thread',
                'verbose_name_plural': 'AI Threads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=16)),
                ('text', models.TextField()),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.aithread')),
            ],
            options={
                'verbose_name': 'AI Message',
                'verbose_name_plural': 'AI Messages',
                'ordering': ['at'],
            },
        ),
        migrations.AddIndex(
            model_name='aithread',
            index=models.Index(fields=['user', 'feature'], name='ai_aithread_user_id_452fcf_idx'),
        ),
        migrations.AddConstraint(
            model_name='aithread',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('user', 'feature'), name='uniq_ai_thread_user_feature_active'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['thread', 'at'], name='ai_aimessag_thread__41a9c0_idx'),
        ),
    ]
