# Generated by Django 4.2.30 on 2026-07-09 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, help_text='Head of Department (must be a faculty/hod-role user).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_departments', to=settings.AUTH_USER_MODEL),
        ),
    ]
