# Generated by Django 4.2.30 on 2026-07-09 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_add_hod_to_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Assigned faculty member for this subject.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_teaching', to=settings.AUTH_USER_MODEL),
        ),
    ]
