# Generated by Django 4.2.30 on 2026-07-09 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_add_faculty_to_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='The semester this subject is taught in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.semester'),
        ),
    ]
