# Generated by Django 4.2.30 on 2026-07-09 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0004_add_semester_to_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='faculty',
            field=models.ForeignKey(blank=True, help_text='Faculty taking this session (overrides subject default).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
