# Generated by Django 4.2.30 on 2026-07-09 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_add_faculty_to_classsession'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='uniq_attendance_student_subject_date',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='period',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Period number (e.g. 1, 2, 3...) for the day.', null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The timetable period/slot this attendance was marked for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='academics.classsession'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='period',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Period number for the day (1, 2, 3...).', null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session',
            field=models.ForeignKey(blank=True, help_text='The timetable slot this attendance session corresponds to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='academics.classsession'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session'], name='attendance__session_db5b8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student', 'subject', 'date', 'period'), name='uniq_attendance_student_subject_date_period'),
        ),
    ]
